### ISSUE TITLE
potential large ISO size due to krita

### ISSUE THREAD

**Issue by fossfreedom** [ubuntucinnamonremix/ubuntucinnamon-meta#12]
What's the reasoning behind the choice of krita?

It will pull in virtually all of the KDE stack which is huge just for one app.  Potentially making the ISO size much larger. 

You also will have the issue of trying to get a QT app the same look and feel as the other GTK3 apps.

**Comment by ubuntucinnamonremix** [comment]
There is no extra KDE to be installed, here is our code:

sudo apt-get purge kubuntu-* kde-* plasma-*
[sudo] password for jpeisach: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'kubuntu-docs' for glob 'kubuntu-*'
Note, selecting 'kubuntu-driver-manager' for glob 'kubuntu-*'
Note, selecting 'kubuntu-settings-desktop' for glob 'kubuntu-*'
Note, selecting 'kubuntu-restricted-extras' for glob 'kubuntu-*'
Note, selecting 'kubuntu-default-settings' for glob 'kubuntu-*'
Note, selecting 'kubuntu-patched-l10n' for glob 'kubuntu-*'
Note, selecting 'kubuntu-desktop' for glob 'kubuntu-*'
Note, selecting 'kubuntu-restricted-addons' for glob 'kubuntu-*'
Note, selecting 'kubuntu-dev-tools' for glob 'kubuntu-*'
Note, selecting 'kubuntu-firefox-installer' for glob 'kubuntu-*'
Note, selecting 'kubuntu-debug-installer-dbg' for glob 'kubuntu-*'
Note, selecting 'kubuntu-wallpapers' for glob 'kubuntu-*'
Note, selecting 'kubuntu-full' for glob 'kubuntu-*'
Note, selecting 'kubuntu-notification-helper-dbg' for glob 'kubuntu-*'
Note, selecting 'kubuntu-wallpapers-bionic' for glob 'kubuntu-*'
Note, selecting 'kubuntu-notification-helper' for glob 'kubuntu-*'
Note, selecting 'kubuntu-driver-manager-dbg' for glob 'kubuntu-*'
Note, selecting 'kubuntu-debug-installer' for glob 'kubuntu-*'
Note, selecting 'kubuntu-web-shortcuts' for glob 'kubuntu-*'
Package 'kubuntu-firefox-installer' is not installed, so not removed
Package 'kubuntu-default-settings' is not installed, so not removed
Package 'kubuntu-dev-tools' is not installed, so not removed
Note, selecting 'kde-baseapps-bin' for glob 'kde-*'
Note, selecting 'kde-config-fcitx' for glob 'kde-*'
Note, selecting 'kde-telepathy-data' for glob 'kde-*'
Note, selecting 'kde-telepathy-contact-list' for glob 'kde-*'
Note, selecting 'kde-l10n-ast' for glob 'kde-*'
Note, selecting 'kde-config-touchpad' for glob 'kde-*'
Note, selecting 'kde-cli-tools' for glob 'kde-*'
Note, selecting 'kde-config-gtk-style' for glob 'kde-*'
Note, selecting 'kde-full' for glob 'kde-*'
Note, selecting 'kde-config-cddb' for glob 'kde-*'
Note, selecting 'kde-window-manager' for glob 'kde-*'
Note, selecting 'kde-config-gtk-style-preview' for glob 'kde-*'
Note, selecting 'kde-workspace' for glob 'kde-*'
Note, selecting 'kde-telepathy-integration-module' for glob 'kde-*'
Note, selecting 'kde-config-whoopsie' for glob 'kde-*'
Note, selecting 'kde-runtime' for glob 'kde-*'
Note, selecting 'kde-telepathy-declarative' for glob 'kde-*'
Note, selecting 'kde-telepathy-send-file' for glob 'kde-*'
Note, selecting 'kde-telepathy-kaccounts' for glob 'kde-*'
Note, selecting 'kde-style-breeze' for glob 'kde-*'
Note, selecting 'kde-style-oxygen' for glob 'kde-*'
Note, selecting 'kde-workspace-data' for glob 'kde-*'
Note, selecting 'kde-telepathy' for glob 'kde-*'
Note, selecting 'kde-style-oxygen-qt5' for glob 'kde-*'
Note, selecting 'kde-zeroconf' for glob 'kde-*'
Note, selecting 'kde-l10n-nds' for glob 'kde-*'
Note, selecting 'kde-style-qtcurve-qt4' for glob 'kde-*'
Note, selecting 'kde-style-qtcurve-qt5' for glob 'kde-*'
Note, selecting 'kde-config-systemd' for glob 'kde-*'
Note, selecting 'kde-config-cron' for glob 'kde-*'
Note, selecting 'kde-telepathy-call-ui' for glob 'kde-*'
Note, selecting 'kde-config-telepathy-accounts' for glob 'kde-*'
Note, selecting 'kde-standard' for glob 'kde-*'
Note, selecting 'kde-cli-tools-data' for glob 'kde-*'
Note, selecting 'kde-telepathy-auth-handler' for glob 'kde-*'
Note, selecting 'kde-l10n-ar' for glob 'kde-*'
Note, selecting 'kde-l10n-bg' for glob 'kde-*'
Note, selecting 'kde-l10n-bs' for glob 'kde-*'
Note, selecting 'kde-l10n-ca' for glob 'kde-*'
Note, selecting 'kde-l10n-cs' for glob 'kde-*'
Note, selecting 'kde-l10n-da' for glob 'kde-*'
Note, selecting 'kde-l10n-de' for glob 'kde-*'
Note, selecting 'kde-plasma-desktop' for glob 'kde-*'
Note, selecting 'kde-l10n-el' for glob 'kde-*'
Note, selecting 'kde-l10n-eo' for glob 'kde-*'
Note, selecting 'kde-l10n-es' for glob 'kde-*'
Note, selecting 'kde-l10n-et' for glob 'kde-*'
Note, selecting 'kde-l10n-eu' for glob 'kde-*'
Note, selecting 'kde-l10n-fa' for glob 'kde-*'
Note, selecting 'kde-l10n-fi' for glob 'kde-*'
Note, selecting 'kde-l10n-fr' for glob 'kde-*'
Note, selecting 'kde-l10n-ga' for glob 'kde-*'
Note, selecting 'kde-l10n-gl' for glob 'kde-*'
Note, selecting 'kde-l10n-he' for glob 'kde-*'
Note, selecting 'kde-l10n-hi' for glob 'kde-*'
Note, selecting 'kde-l10n-hr' for glob 'kde-*'
Note, selecting 'kde-l10n-hu' for glob 'kde-*'
Note, selecting 'kde-l10n-ia' for glob 'kde-*'
Note, selecting 'kde-l10n-id' for glob 'kde-*'
Note, selecting 'kde-l10n-is' for glob 'kde-*'
Note, selecting 'kde-l10n-it' for glob 'kde-*'
Note, selecting 'kde-l10n-ja' for glob 'kde-*'
Note, selecting 'kde-l10n-kk' for glob 'kde-*'
Note, selecting 'kde-l10n-km' for glob 'kde-*'
Note, selecting 'kde-l10n-ko' for glob 'kde-*'
Note, selecting 'kde-l10n-lt' for glob 'kde-*'
Note, selecting 'kde-l10n-lv' for glob 'kde-*'
Note, selecting 'kde-l10n-mr' for glob 'kde-*'
Note, selecting 'kde-l10n-nb' for glob 'kde-*'
Note, selecting 'kde-l10n-nl' for glob 'kde-*'
Note, selecting 'kde-l10n-nn' for glob 'kde-*'
Note, selecting 'kde-l10n-pa' for glob 'kde-*'
Note, selecting 'kde-l10n-pl' for glob 'kde-*'
Note, selecting 'kde-l10n-pt' for glob 'kde-*'
Note, selecting 'kde-baseapps' for glob 'kde-*'
Note, selecting 'kde-l10n-ro' for glob 'kde-*'
Note, selecting 'kde-l10n-ru' for glob 'kde-*'
Note, selecting 'kde-l10n-si' for glob 'kde-*'
Note, selecting 'kde-l10n-sk' for glob 'kde-*'
Note, selecting 'kde-l10n-sl' for glob 'kde-*'
Note, selecting 'kde-l10n-sr' for glob 'kde-*'
Note, selecting 'kde-l10n-sv' for glob 'kde-*'
Note, selecting 'kde-l10n-tg' for glob 'kde-*'
Note, selecting 'kde-l10n-th' for glob 'kde-*'
Note, selecting 'kde-l10n-tr' for glob 'kde-*'
Note, selecting 'kde-l10n-ug' for glob 'kde-*'
Note, selecting 'kde-l10n-uk' for glob 'kde-*'
Note, selecting 'kde-l10n-wa' for glob 'kde-*'
Note, selecting 'kde-telepathy-text-ui' for glob 'kde-*'
Note, selecting 'kde-config-sddm' for glob 'kde-*'
Note, selecting 'kde-l10n-zhcn' for glob 'kde-*'
Note, selecting 'kde-l10n-zhtw' for glob 'kde-*'
Note, selecting 'kde-telepathy-minimal' for glob 'kde-*'
Note, selecting 'kde-telepathy-desktop-applets' for glob 'kde-*'
Note, selecting 'kde-minimal' for glob 'kde-*'
Note, selecting 'kde-wallpapers' for glob 'kde-*'
Note, selecting 'kde-config-mailtransport' for glob 'kde-*'
Note, selecting 'kde-l10n-cavalencia' for glob 'kde-*'
Note, selecting 'kde-l10n-ptbr' for glob 'kde-*'
Note, selecting 'kde-thumbnailer-deb' for glob 'kde-*'
Note, selecting 'kde-l10n-engb' for glob 'kde-*'
Note, selecting 'kde-telepathy-kpeople' for glob 'kde-*'
Note, selecting 'kde-telepathy-legacy-presence-applet' for glob 'kde-*'
Note, selecting 'kde-service-menu-fuseiso' for glob 'kde-*'
Note, selecting 'kde-config-tablet' for glob 'kde-*'
Note, selecting 'kde-software-compilation' for glob 'kde-*'
Note, selecting 'kde-wallpapers-default' for glob 'kde-*'
Note, selecting 'kde-config-plymouth' for glob 'kde-*'
Note, selecting 'kde-telepathy-filetransfer-handler' for glob 'kde-*'
Note, selecting 'kde-l10n' for glob 'kde-*'
Note, selecting 'kde-config-screenlocker' for glob 'kde-*'
Note, selecting 'kde-workspace-bin' for glob 'kde-*'
Note, selecting 'kde-telepathy-approver' for glob 'kde-*'
Note, selecting 'kde-workspace-dev' for glob 'kde-*'
Note, selecting 'kde-spectacle' for glob 'kde-*'
Note, selecting 'kde-telepathy-debugger' for glob 'kde-*'
Package 'kde-baseapps-bin' is not installed, so not removed
Package 'kde-l10n-ar' is not installed, so not removed
Package 'kde-l10n-ast' is not installed, so not removed
Package 'kde-l10n-bg' is not installed, so not removed
Package 'kde-l10n-bs' is not installed, so not removed
Package 'kde-l10n-ca' is not installed, so not removed
Package 'kde-l10n-cavalencia' is not installed, so not removed
Package 'kde-l10n-cs' is not installed, so not removed
Package 'kde-l10n-da' is not installed, so not removed
Package 'kde-l10n-de' is not installed, so not removed
Package 'kde-l10n-el' is not installed, so not removed
Package 'kde-l10n-engb' is not installed, so not removed
Package 'kde-l10n-eo' is not installed, so not removed
Package 'kde-l10n-es' is not installed, so not removed
Package 'kde-l10n-et' is not installed, so not removed
Package 'kde-l10n-eu' is not installed, so not removed
Package 'kde-l10n-fa' is not installed, so not removed
Package 'kde-l10n-fi' is not installed, so not removed
Package 'kde-l10n-fr' is not installed, so not removed
Package 'kde-l10n-ga' is not installed, so not removed
Package 'kde-l10n-gl' is not installed, so not removed
Package 'kde-l10n-he' is not installed, so not removed
Package 'kde-l10n-hi' is not installed, so not removed
Package 'kde-l10n-hr' is not installed, so not removed
Package 'kde-l10n-hu' is not installed, so not removed
Package 'kde-l10n-ia' is not installed, so not removed
Package 'kde-l10n-id' is not installed, so not removed
Package 'kde-l10n-is' is not installed, so not removed
Package 'kde-l10n-it' is not installed, so not removed
Package 'kde-l10n-ja' is not installed, so not removed
Package 'kde-l10n-kk' is not installed, so not removed
Package 'kde-l10n-km' is not installed, so not removed
Package 'kde-l10n-ko' is not installed, so not removed
Package 'kde-l10n-lt' is not installed, so not removed
Package 'kde-l10n-lv' is not installed, so not removed
Package 'kde-l10n-mr' is not installed, so not removed
Package 'kde-l10n-nb' is not installed, so not removed
Package 'kde-l10n-nds' is not installed, so not removed
Package 'kde-l10n-nl' is not installed, so not removed
Package 'kde-l10n-nn' is not installed, so not removed
Package 'kde-l10n-pa' is not installed, so not removed
Package 'kde-l10n-pl' is not installed, so not removed
Package 'kde-l10n-pt' is not installed, so not removed
Package 'kde-l10n-ptbr' is not installed, so not removed
Package 'kde-l10n-ro' is not installed, so not removed
Package 'kde-l10n-ru' is not installed, so not removed
Package 'kde-l10n-sk' is not installed, so not removed
Package 'kde-l10n-sl' is not installed, so not removed
Package 'kde-l10n-sr' is not installed, so not removed
Package 'kde-l10n-sv' is not installed, so not removed
Package 'kde-l10n-tr' is not installed, so not removed
Package 'kde-l10n-ug' is not installed, so not removed
Package 'kde-l10n-uk' is not installed, so not removed
Package 'kde-l10n-wa' is not installed, so not removed
Package 'kde-l10n-zhcn' is not installed, so not removed
Package 'kde-l10n-zhtw' is not installed, so not removed
Package 'kde-minimal' is not installed, so not removed
Note, selecting 'kde-full' instead of 'kde-software-compilation'
Package 'kde-style-qtcurve-qt4' is not installed, so not removed
Package 'kde-workspace-dev' is not installed, so not removed
Package 'kde-l10n-si' is not installed, so not removed
Package 'kde-l10n-tg' is not installed, so not removed
Package 'kde-l10n-th' is not installed, so not removed
Package 'kde-wallpapers' is not installed, so not removed
Package 'kde-wallpapers-default' is not installed, so not removed
Package 'kde-l10n' is not installed, so not removed
Package 'kde-runtime' is not installed, so not removed
Package 'kde-workspace' is not installed, so not removed
Package 'kde-workspace-bin' is not installed, so not removed
Package 'kde-workspace-data' is not installed, so not removed
Package 'kde-telepathy-declarative' is not installed, so not removed
Note, selecting 'plasma-workspace' for glob 'plasma-*'
Note, selecting 'plasma-discover-snap-backend' for glob 'plasma-*'
Note, selecting 'plasma-widget-milou-kf5' for glob 'plasma-*'
Note, selecting 'plasma-kdevelop' for glob 'plasma-*'
Note, selecting 'plasma-nm-data' for glob 'plasma-*'
Note, selecting 'plasma-nm' for glob 'plasma-*'
Note, selecting 'plasma-pa' for glob 'plasma-*'
Note, selecting 'plasma-dataengines-addons' for glob 'plasma-*'
Note, selecting 'plasma-widget-telepathy-chat' for glob 'plasma-*'
Note, selecting 'plasma-sdk' for glob 'plasma-*'
Note, selecting 'plasma-wallpapers-addons' for glob 'plasma-*'
Note, selecting 'plasma-theme-oxygen' for glob 'plasma-*'
Note, selecting 'plasma-discover-backend-snap' for glob 'plasma-*'
Note, selecting 'plasma-discover-common' for glob 'plasma-*'
Note, selecting 'plasma-runner-installer' for glob 'plasma-*'
Note, selecting 'plasma-discover' for glob 'plasma-*'
Note, selecting 'plasma-desktop' for glob 'plasma-*'
Note, selecting 'plasma-workspace-wayland' for glob 'plasma-*'
Note, selecting 'plasma-vault' for glob 'plasma-*'
Note, selecting 'plasma-desktop-data' for glob 'plasma-*'
Note, selecting 'plasma-gmailfeed' for glob 'plasma-*'
Note, selecting 'plasma-framework-dev' for glob 'plasma-*'
Note, selecting 'plasma-runners-addons' for glob 'plasma-*'
Note, selecting 'plasma-widget-kimpanel' for glob 'plasma-*'
Note, selecting 'plasma-browser-integration' for glob 'plasma-*'
Note, selecting 'plasma-workspace-data' for glob 'plasma-*'
Note, selecting 'plasma-discover-flatpak-backend' for glob 'plasma-*'
Note, selecting 'plasma-desktop-dev' for glob 'plasma-*'
Note, selecting 'plasma-systray-legacy' for glob 'plasma-*'
Note, selecting 'plasma-widget-telepathy-presence' for glob 'plasma-*'
Note, selecting 'plasma-integration' for glob 'plasma-*'
Note, selecting 'plasma-workspace-dev' for glob 'plasma-*'
Note, selecting 'plasma-applet-redshift-control' for glob 'plasma-*'
Note, selecting 'plasma-marble' for glob 'plasma-*'
Note, selecting 'plasma-framework' for glob 'plasma-*'
Note, selecting 'plasma-discover-backend-flatpak' for glob 'plasma-*'
Note, selecting 'plasma-calendar-addons' for glob 'plasma-*'
Note, selecting 'plasma-look-and-feel-org-kde-breezedark-desktop' for glob 'plasma-*'
Note, selecting 'plasma-discover-updater' for glob 'plasma-*'
Note, selecting 'plasma-workspace-wallpapers' for glob 'plasma-*'
Note, selecting 'plasma-widget-networkmanagement' for glob 'plasma-*'
Note, selecting 'plasma-widgets-kimpanel' for glob 'plasma-*'
Note, selecting 'plasma-runner-telepathy-contact' for glob 'plasma-*'
Note, selecting 'plasma-widgets-addons' for glob 'plasma-*'
Note, selecting 'plasma-discover-private' for glob 'plasma-*'
Package 'plasma-widgets-kimpanel' is not installed, so not removed
Package 'plasma-widget-telepathy-chat' is not installed, so not removed
Package 'plasma-widget-telepathy-presence' is not installed, so not removed
Package 'plasma-framework-dev' is not installed, so not removed
Package 'plasma-widget-milou-kf5' is not installed, so not removed
Package 'plasma-widget-networkmanagement' is not installed, so not removed
Package 'plasma-widget-kimpanel' is not installed, so not removed
Package 'plasma-discover-private' is not installed, so not removed
Package 'plasma-discover-updater' is not installed, so not removed
Package 'plasma-nm-data' is not installed, so not removed
Package 'plasma-systray-legacy' is not installed, so not removed
Package 'plasma-workspace-data' is not installed, so not removed
Package 'kde-baseapps' is not installed, so not removed
Package 'kde-cli-tools' is not installed, so not removed
Package 'kde-cli-tools-data' is not installed, so not removed
Package 'kde-config-cddb' is not installed, so not removed
Package 'kde-config-cron' is not installed, so not removed
Package 'kde-config-fcitx' is not installed, so not removed
Package 'kde-config-gtk-style' is not installed, so not removed
Package 'kde-config-gtk-style-preview' is not installed, so not removed
Package 'kde-config-mailtransport' is not installed, so not removed
Package 'kde-config-plymouth' is not installed, so not removed
Package 'kde-config-screenlocker' is not installed, so not removed
Package 'kde-config-sddm' is not installed, so not removed
Package 'kde-config-systemd' is not installed, so not removed
Package 'kde-config-tablet' is not installed, so not removed
Package 'kde-config-telepathy-accounts' is not installed, so not removed
Package 'kde-config-touchpad' is not installed, so not removed
Package 'kde-config-whoopsie' is not installed, so not removed
Package 'kde-full' is not installed, so not removed
Package 'kde-plasma-desktop' is not installed, so not removed
Package 'kde-service-menu-fuseiso' is not installed, so not removed
Package 'kde-spectacle' is not installed, so not removed
Package 'kde-standard' is not installed, so not removed
Package 'kde-style-breeze' is not installed, so not removed
Package 'kde-style-oxygen' is not installed, so not removed
Package 'kde-style-oxygen-qt5' is not installed, so not removed
Package 'kde-style-qtcurve-qt5' is not installed, so not removed
Package 'kde-telepathy' is not installed, so not removed
Package 'kde-telepathy-approver' is not installed, so not removed
Package 'kde-telepathy-auth-handler' is not installed, so not removed
Package 'kde-telepathy-call-ui' is not installed, so not removed
Package 'kde-telepathy-contact-list' is not installed, so not removed
Package 'kde-telepathy-data' is not installed, so not removed
Package 'kde-telepathy-debugger' is not installed, so not removed
Package 'kde-telepathy-desktop-applets' is not installed, so not removed
Package 'kde-telepathy-filetransfer-handler' is not installed, so not removed
Package 'kde-telepathy-integration-module' is not installed, so not removed
Package 'kde-telepathy-kaccounts' is not installed, so not removed
Package 'kde-telepathy-kpeople' is not installed, so not removed
Package 'kde-telepathy-legacy-presence-applet' is not installed, so not removed
Package 'kde-telepathy-minimal' is not installed, so not removed
Package 'kde-telepathy-send-file' is not installed, so not removed
Package 'kde-telepathy-text-ui' is not installed, so not removed
Package 'kde-thumbnailer-deb' is not installed, so not removed
Package 'kde-window-manager' is not installed, so not removed
Package 'kde-zeroconf' is not installed, so not removed
Package 'kubuntu-debug-installer' is not installed, so not removed
Package 'kubuntu-debug-installer-dbg' is not installed, so not removed
Package 'kubuntu-desktop' is not installed, so not removed
Package 'kubuntu-docs' is not installed, so not removed
Package 'kubuntu-driver-manager' is not installed, so not removed
Package 'kubuntu-driver-manager-dbg' is not installed, so not removed
Package 'kubuntu-full' is not installed, so not removed
Package 'kubuntu-notification-helper' is not installed, so not removed
Package 'kubuntu-notification-helper-dbg' is not installed, so not removed
Package 'kubuntu-patched-l10n' is not installed, so not removed
Package 'kubuntu-settings-desktop' is not installed, so not removed
Package 'kubuntu-wallpapers' is not installed, so not removed
Package 'kubuntu-wallpapers-bionic' is not installed, so not removed
Package 'kubuntu-web-shortcuts' is not installed, so not removed
Package 'plasma-applet-redshift-control' is not installed, so not removed
Package 'plasma-browser-integration' is not installed, so not removed
Package 'plasma-calendar-addons' is not installed, so not removed
Package 'plasma-dataengines-addons' is not installed, so not removed
Package 'plasma-desktop' is not installed, so not removed
Package 'plasma-desktop-data' is not installed, so not removed
Package 'plasma-desktop-dev' is not installed, so not removed
Package 'plasma-discover' is not installed, so not removed
Package 'plasma-discover-backend-flatpak' is not installed, so not removed
Package 'plasma-discover-backend-snap' is not installed, so not removed
Package 'plasma-discover-common' is not installed, so not removed
Package 'plasma-discover-flatpak-backend' is not installed, so not removed
Package 'plasma-discover-snap-backend' is not installed, so not removed
Package 'plasma-framework' is not installed, so not removed
Package 'plasma-gmailfeed' is not installed, so not removed
Package 'plasma-integration' is not installed, so not removed
Package 'plasma-kdevelop' is not installed, so not removed
Package 'plasma-look-and-feel-org-kde-breezedark-desktop' is not installed, so not removed
Package 'plasma-marble' is not installed, so not removed
Package 'plasma-nm' is not installed, so not removed
Package 'plasma-pa' is not installed, so not removed
Package 'plasma-runner-installer' is not installed, so not removed
Package 'plasma-runner-telepathy-contact' is not installed, so not removed
Package 'plasma-runners-addons' is not installed, so not removed
Package 'plasma-sdk' is not installed, so not removed
Package 'plasma-theme-oxygen' is not installed, so not removed
Package 'plasma-vault' is not installed, so not removed
Package 'plasma-wallpapers-addons' is not installed, so not removed
Package 'plasma-widgets-addons' is not installed, so not removed
Package 'plasma-workspace' is not installed, so not removed
Package 'plasma-workspace-dev' is not installed, so not removed
Package 'plasma-workspace-wallpapers' is not installed, so not removed
Package 'plasma-workspace-wayland' is not installed, so not removed
Package 'kubuntu-restricted-addons' is not installed, so not removed
Package 'kubuntu-restricted-extras' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
jpeisach@Josh-UbuntuCinnamonRepoBuilding:~/Desktop/Ubuntu-Cinnamon$ sudo apt-get install krita
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gdal-data krita-data krita-gmic libaec0 libarmadillo9 libarpack2 libcharls2
  libdap25 libdapclient6v5 libepsilon1 libfreexl1 libfyba0 libgdal20
  libgdcm2.8 libgeos-3.7.2 libgeos-c1v5 libgeotiff2 libgmic1
  libgraphicsmagick++-q16-12 libgraphicsmagick-q16-3 libhdf4-0-alt libhdf5-103
  libkmlbase1 libkmldom1 libkmlengine1 libnetcdf13 libodbc1 libogdi4.1
  libopencolorio1v5 libopencv-core3.2 libopencv-imgcodecs3.2
  libopencv-imgproc3.2 libopencv-videoio3.2 libpoppler-qt5-1 libpq5 libproj13
  libqhull7 libquazip5-1 libsocket++1 libspatialite7 libsuperlu5 libsz2
  libtbb2 liburiparser1 libxerces-c3.2 odbcinst odbcinst1debian2 proj-bin
  proj-data
Suggested packages:
  krita-l10n geotiff-bin gdal-bin libgeotiff-epsg graphicsmagick-dbg
  libhdf4-doc libhdf4-alt-dev hdf4-tools libmyodbc odbc-postgresql tdsodbc
  unixodbc-bin ogdi-bin libquazip-doc
The following NEW packages will be installed:
  gdal-data krita krita-data krita-gmic libaec0 libarmadillo9 libarpack2
  libcharls2 libdap25 libdapclient6v5 libepsilon1 libfreexl1 libfyba0
  libgdal20 libgdcm2.8 libgeos-3.7.2 libgeos-c1v5 libgeotiff2 libgmic1
  libgraphicsmagick++-q16-12 libgraphicsmagick-q16-3 libhdf4-0-alt libhdf5-103
  libkmlbase1 libkmldom1 libkmlengine1 libnetcdf13 libodbc1 libogdi4.1
  libopencolorio1v5 libopencv-core3.2 libopencv-imgcodecs3.2
  libopencv-imgproc3.2 libopencv-videoio3.2 libpoppler-qt5-1 libpq5 libproj13
  libqhull7 libquazip5-1 libsocket++1 libspatialite7 libsuperlu5 libsz2
  libtbb2 liburiparser1 libxerces-c3.2 odbcinst odbcinst1debian2 proj-bin
  proj-data
0 upgraded, 50 newly installed, 0 to remove and 1 not upgraded.
Need to get 95.9 MB of archives.
After this operation, 286 MB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by ubuntucinnamonremix** [comment]
If any extra package was to be installed it'd be libraries.

**Comment by fossfreedom** [comment]
Just install krita on a clean iso then you will see what I am talking about
